### ISSUE TITLE
Cannot access 'err' before initialization #4

### ISSUE THREAD

**Issue by lvenier** [peterprib/node-red-contrib-kafka-manager#5]
follow up #4 

Thanks for the update,

It is now failing for existing topic :(
ReferenceError: err is not defined
    at msgProcess (/home/lav/.node-red/node_modules/node-red-contrib-kafka-manager/kafkaManager/kafkaAdmin.js:20:34)
    at /home/lav/.node-red/node_modules/node-red-contrib-kafka-manager/kafkaManager/kafkaAdmin.js:83:58
    at /home/lav/.node-red/node_modules/kafka-node/lib/kafkaClient.js:1430:5
    at /home/lav/.node-red/node_modules/async/dist/async.js:3888:9
    at /home/lav/.node-red/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/home/lav/.node-red/node_modules/async/dist/async.js:992:24)
    at /home/lav/.node-red/node_modules/async/dist/async.js:969:16
    at /home/lav/.node-red/node_modules/async/dist/async.js:3885:13
    at KafkaClient.wrappedFn (/home/lav/.node-red/node_modules/kafka-node/lib/kafkaClient.js:481:14)
    at KafkaClient.Client.invokeResponseCallback (/home/lav/.node-red/node_modules/kafka-node/lib/baseClient.js:593:10)

**Comment by lvenier** [comment]
that should do it : 
 https://github.com/peterprib/node-red-contrib-kafka-manager/pull/6

**Comment by peterprib** [comment]
Have added your fixes into latest build and published.  Sorry about not properly testing this area.  Need to update tests.  Will close on assumption you have tested and all is OK.  Distract at moment with other matters.
